// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:schemantic/schemantic.dart';

import 'types.dart';
part 'experimental_types.g.dart';

extension type AgentFinishReason(String value) {
  static AgentFinishReason get stop => AgentFinishReason('stop');
  static AgentFinishReason get length => AgentFinishReason('length');
  static AgentFinishReason get blocked => AgentFinishReason('blocked');
  static AgentFinishReason get interrupted => AgentFinishReason('interrupted');
  static AgentFinishReason get other => AgentFinishReason('other');
  static AgentFinishReason get unknown => AgentFinishReason('unknown');
  static AgentFinishReason get aborted => AgentFinishReason('aborted');
  static AgentFinishReason get detached => AgentFinishReason('detached');
  static AgentFinishReason get failed => AgentFinishReason('failed');
}

@Schema()
abstract class $AgentInit {
  String? get sessionId;
  String? get snapshotId;
  $SessionState? get state;
}

@Schema()
abstract class $AgentInput {
  bool? get detach;
  $Message? get message;
  $AgentResume? get resume;
}

@Schema()
abstract class $AgentResume {
  List<$ToolResponsePart>? get respond;
  List<$ToolRequestPart>? get restart;
}

@Schema()
abstract class $AgentOutput {
  String? get sessionId;
  String? get snapshotId;
  $SessionState? get state;
  $Message? get message;
  List<$Artifact>? get artifacts;
  AgentFinishReason? get finishReason;
  $AgentErrorInfo? get error;
}

@Schema()
abstract class $AgentErrorInfo {
  String? get status;
  String get message;
  Object? get details;
}

@Schema()
abstract class $AgentResult {
  $Message? get message;
  List<$Artifact>? get artifacts;
  AgentFinishReason? get finishReason;
}

@Schema()
abstract class $AgentStreamChunk {
  $ModelResponseChunk? get modelChunk;
  List<$JsonPatchOperation>? get customPatch;
  $Artifact? get artifact;
  $TurnEnd? get turnEnd;
}

@Schema()
abstract class $AgentAbortRequest {
  String get snapshotId;
}

@Schema()
abstract class $AgentAbortResponse {
  String get snapshotId;
  SnapshotStatus? get status;
}

@Schema()
abstract class $AgentMetadata {
  AgentStateManagement get stateManagement;
  bool get abortable;
  Map<String, dynamic>? get stateSchema;
}

extension type AgentStateManagement(String value) {
  static AgentStateManagement get server => AgentStateManagement('server');
  static AgentStateManagement get client => AgentStateManagement('client');
}

@Schema()
abstract class $TurnEnd {
  String? get snapshotId;
  AgentFinishReason? get finishReason;
}

@Schema()
abstract class $Artifact {
  String? get name;
  List<$Part> get parts;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $GetSnapshotDataInput {
  String? get snapshotId;
  String? get sessionId;
  bool? get metadataOnly;
}

extension type JsonPatchOp(String value) {
  static JsonPatchOp get add => JsonPatchOp('add');
  static JsonPatchOp get remove => JsonPatchOp('remove');
  static JsonPatchOp get replace => JsonPatchOp('replace');
  static JsonPatchOp get move => JsonPatchOp('move');
  static JsonPatchOp get copy => JsonPatchOp('copy');
  static JsonPatchOp get test => JsonPatchOp('test');
}

@Schema()
abstract class $JsonPatchOperation {
  JsonPatchOp get op;
  String get path;
  String? get from;
  Object? get value;
}

@Schema()
abstract class $SessionSnapshot {
  String get snapshotId;
  String? get sessionId;
  String? get parentId;
  String get createdAt;
  String? get updatedAt;
  String? get heartbeatAt;
  SnapshotStatus? get status;
  AgentFinishReason? get finishReason;
  $AgentErrorInfo? get error;
  $SessionState? get state;
}

@Schema()
abstract class $SessionState {
  String? get sessionId;
  List<$Message>? get messages;
  Object? get custom;
  List<$Artifact>? get artifacts;
}

extension type SnapshotStatus(String value) {
  static SnapshotStatus get pending => SnapshotStatus('pending');
  static SnapshotStatus get aborting => SnapshotStatus('aborting');
  static SnapshotStatus get completed => SnapshotStatus('completed');
  static SnapshotStatus get aborted => SnapshotStatus('aborted');
  static SnapshotStatus get failed => SnapshotStatus('failed');
  static SnapshotStatus get expired => SnapshotStatus('expired');
}
