// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:schemantic/schemantic.dart';

import 'types.dart';
part 'experimental_types.g.dart';

extension type const AgentFinishReason(String value) {
  static const AgentFinishReason stop = AgentFinishReason('stop');
  static const AgentFinishReason length = AgentFinishReason('length');
  static const AgentFinishReason blocked = AgentFinishReason('blocked');
  static const AgentFinishReason interrupted = AgentFinishReason('interrupted');
  static const AgentFinishReason other = AgentFinishReason('other');
  static const AgentFinishReason unknown = AgentFinishReason('unknown');
  static const AgentFinishReason aborted = AgentFinishReason('aborted');
  static const AgentFinishReason detached = AgentFinishReason('detached');
  static const AgentFinishReason failed = AgentFinishReason('failed');
}

@Schema()
abstract class $AgentInit {
  String? get sessionId;
  String? get snapshotId;
  $SessionState? get state;
}

@Schema()
abstract class $AgentInput {
  bool? get detach;
  $Message? get message;
  $AgentResume? get resume;
}

@Schema()
abstract class $AgentResume {
  List<$ToolResponsePart>? get respond;
  List<$ToolRequestPart>? get restart;
}

@Schema()
abstract class $AgentOutput {
  String? get sessionId;
  String? get snapshotId;
  $SessionState? get state;
  $Message? get message;
  List<$Artifact>? get artifacts;
  AgentFinishReason? get finishReason;
  $AgentErrorInfo? get error;
}

@Schema()
abstract class $AgentErrorInfo {
  String? get status;
  String get message;
  Object? get details;
}

@Schema()
abstract class $AgentResult {
  $Message? get message;
  List<$Artifact>? get artifacts;
  AgentFinishReason? get finishReason;
}

@Schema()
abstract class $AgentStreamChunk {
  $ModelResponseChunk? get modelChunk;
  List<$JsonPatchOperation>? get customPatch;
  $Artifact? get artifact;
  $TurnEnd? get turnEnd;
}

@Schema()
abstract class $AgentAbortRequest {
  String get snapshotId;
}

@Schema()
abstract class $AgentAbortResponse {
  String get snapshotId;
  SnapshotStatus? get status;
}

@Schema()
abstract class $AgentMetadata {
  AgentStateManagement get stateManagement;
  bool get abortable;
  Map<String, dynamic>? get stateSchema;
}

extension type const AgentStateManagement(String value) {
  static const AgentStateManagement server = AgentStateManagement('server');
  static const AgentStateManagement client = AgentStateManagement('client');
}

@Schema()
abstract class $TurnEnd {
  String? get snapshotId;
  AgentFinishReason? get finishReason;
}

@Schema()
abstract class $Artifact {
  String? get name;
  List<$Part> get parts;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $GetSnapshotDataInput {
  String? get snapshotId;
  String? get sessionId;
  bool? get metadataOnly;
}

extension type const JsonPatchOp(String value) {
  static const JsonPatchOp add = JsonPatchOp('add');
  static const JsonPatchOp remove = JsonPatchOp('remove');
  static const JsonPatchOp replace = JsonPatchOp('replace');
  static const JsonPatchOp move = JsonPatchOp('move');
  static const JsonPatchOp copy = JsonPatchOp('copy');
  static const JsonPatchOp test = JsonPatchOp('test');
}

@Schema()
abstract class $JsonPatchOperation {
  JsonPatchOp get op;
  String get path;
  String? get from;
  Object? get value;
}

@Schema()
abstract class $SessionSnapshot {
  String get snapshotId;
  String? get sessionId;
  String? get parentId;
  String get createdAt;
  String? get updatedAt;
  String? get heartbeatAt;
  SnapshotStatus? get status;
  AgentFinishReason? get finishReason;
  $AgentErrorInfo? get error;
  $SessionState? get state;
}

@Schema()
abstract class $SessionState {
  String? get sessionId;
  List<$Message>? get messages;
  Object? get custom;
  List<$Artifact>? get artifacts;
}

extension type const SnapshotStatus(String value) {
  static const SnapshotStatus pending = SnapshotStatus('pending');
  static const SnapshotStatus aborting = SnapshotStatus('aborting');
  static const SnapshotStatus completed = SnapshotStatus('completed');
  static const SnapshotStatus aborted = SnapshotStatus('aborted');
  static const SnapshotStatus failed = SnapshotStatus('failed');
  static const SnapshotStatus expired = SnapshotStatus('expired');
}
