// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:schemantic/schemantic.dart';
part 'types.g.dart';

@Schematic()
abstract class $Candidate {
  double get index;
  $Message get message;
  $GenerationUsage? get usage;
  FinishReason get finishReason;
  String? get finishMessage;
  Map<String, dynamic>? get custom;
}

@Schematic()
abstract class $Message {
  Role get role;
  List<$Part> get content;
  Map<String, dynamic>? get metadata;
}

@Schematic()
abstract class $ToolDefinition {
  String get name;
  String get description;
  Map<String, dynamic>? get inputSchema;
  Map<String, dynamic>? get outputSchema;
  Map<String, dynamic>? get metadata;
}

@Schematic()
abstract class $Part {}

@Schematic()
abstract class $TextPart implements $Part {
  String get text;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schematic()
abstract class $MediaPart implements $Part {
  $Media get media;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schematic()
abstract class $ToolRequestPart implements $Part {
  $ToolRequest get toolRequest;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schematic()
abstract class $ToolResponsePart implements $Part {
  $ToolResponse get toolResponse;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schematic()
abstract class $DataPart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schematic()
abstract class $CustomPart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic> get custom;
}

@Schematic()
abstract class $ReasoningPart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
  String get reasoning;
}

@Schematic()
abstract class $ResourcePart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
  Map<String, dynamic> get resource;
}

@Schematic()
abstract class $Media {
  String? get contentType;
  String get url;
}

@Schematic()
abstract class $ToolRequest {
  String? get ref;
  String get name;
  Map<String, dynamic>? get input;
  bool? get partial;
}

@Schematic()
abstract class $ToolResponse {
  String? get ref;
  String get name;
  dynamic get output;
  List<dynamic>? get content;
}

@Schematic()
abstract class $ModelInfo {
  List<String>? get versions;
  String? get label;
  Map<String, dynamic>? get configSchema;
  Map<String, dynamic>? get supports;
  String? get stage;
}

@Schematic()
abstract class $ModelRequest {
  List<$Message> get messages;
  Map<String, dynamic>? get config;
  List<$ToolDefinition>? get tools;
  String? get toolChoice;
  $OutputConfig? get output;
  List<$DocumentData>? get docs;
}

@Schematic()
abstract class $ModelResponse {
  $Message? get message;
  FinishReason get finishReason;
  String? get finishMessage;
  double? get latencyMs;
  $GenerationUsage? get usage;
  Map<String, dynamic>? get custom;
  Map<String, dynamic>? get raw;
  $GenerateRequest? get request;
  $Operation? get operation;
}

@Schematic()
abstract class $ModelResponseChunk {
  Role? get role;
  int? get index;
  List<$Part> get content;
  Map<String, dynamic>? get custom;
  bool? get aggregated;
}

@Schematic()
abstract class $GenerateResponse {
  $Message? get message;
  FinishReason? get finishReason;
  String? get finishMessage;
  double? get latencyMs;
  $GenerationUsage? get usage;
  Map<String, dynamic>? get custom;
  Map<String, dynamic>? get raw;
  $GenerateRequest? get request;
  $Operation? get operation;
  List<$Candidate>? get candidates;
}

@Schematic()
abstract class $GenerateRequest {
  List<$Message> get messages;
  Map<String, dynamic>? get config;
  List<$ToolDefinition>? get tools;
  String? get toolChoice;
  $OutputConfig? get output;
  List<$DocumentData>? get docs;
  double? get candidates;
}

@Schematic()
abstract class $GenerationUsage {
  double? get inputTokens;
  double? get outputTokens;
  double? get totalTokens;
  double? get inputCharacters;
  double? get outputCharacters;
  double? get inputImages;
  double? get outputImages;
  double? get inputVideos;
  double? get outputVideos;
  double? get inputAudioFiles;
  double? get outputAudioFiles;
  Map<String, dynamic>? get custom;
  double? get thoughtsTokens;
  double? get cachedContentTokens;
}

@Schematic()
abstract class $Operation {
  String? get action;
  String get id;
  bool? get done;
  Map<String, dynamic>? get output;
  Map<String, dynamic>? get error;
  Map<String, dynamic>? get metadata;
}

@Schematic()
abstract class $OutputConfig {
  String? get format;
  Map<String, dynamic>? get schema;
  bool? get constrained;
  String? get contentType;
}

extension type FinishReason(String value) {
  static FinishReason get stop => FinishReason('stop');
  static FinishReason get length => FinishReason('length');
  static FinishReason get blocked => FinishReason('blocked');
  static FinishReason get interrupted => FinishReason('interrupted');
  static FinishReason get other => FinishReason('other');
  static FinishReason get unknown => FinishReason('unknown');
}
extension type Role(String value) {
  static Role get system => Role('system');
  static Role get user => Role('user');
  static Role get model => Role('model');
  static Role get tool => Role('tool');
}

@Schematic()
abstract class $DocumentData {
  List<$Part> get content;
  Map<String, dynamic>? get metadata;
}

@Schematic()
abstract class $GenerateActionOptions {
  String? get model;
  List<$DocumentData>? get docs;
  List<$Message> get messages;
  List<String>? get tools;
  String? get toolChoice;
  Map<String, dynamic>? get config;
  $GenerateActionOutputConfig? get output;
  Map<String, dynamic>? get resume;
  bool? get returnToolRequests;
  int? get maxTurns;
  String? get stepName;
}

@Schematic()
abstract class $GenerateActionOutputConfig {
  String? get format;
  String? get contentType;
  @AnyOf([bool, String])
  Object? get instructions;
  Map<String, dynamic>? get jsonSchema;
  bool? get constrained;
}
