# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the lints from `package:dart_flutter_team_lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.

include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-inference: false

  errors:
    lines_longer_than_80_chars: ignore
    prefer_const_constructors: ignore
    unawaited_futures: ignore
    unreachable_from_main: ignore

linter:
  rules:
    - unnecessary_breaks
    - unnecessary_ignore
