# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors: 
    # many doc comments to fix
    lines_longer_than_80_chars: ignore
