targets:
  $default:
    builders:
      schema_builder:
        enabled: true

builders:
  schema_builder:
    target: ":schema_builder"
    import: "package:schema_builder/builder.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: {".dart": [".schema.g.dart"]}
    auto_apply: dependents
    build_to: source
