builders:
  schemantic:
    import: "package:schemantic/builder.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: {".dart": [".schema.g.dart"]}
    auto_apply: dependents
    build_to: source

targets:
  $default:
    builders:
      schemantic:
        enabled: true
