// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:schemantic/schemantic.dart';
part 'reflection_types.g.dart';

@Schema()
abstract class $ReflectionCancelActionParams {
  String get traceId;
}

@Schema()
abstract class $ReflectionCancelActionResponse {
  String get message;
}

@Schema()
abstract class $ReflectionConfigureParams {
  String? get telemetryServerUrl;
}

@Schema()
abstract class $ReflectionEndInputStreamParams {
  String get requestId;
}

@Schema()
abstract class $ReflectionListActionsResponse {
  Map<String, dynamic> get actions;
}

@Schema()
abstract class $ReflectionListValuesParams {
  String get type;
}

@Schema()
abstract class $ReflectionListValuesResponse {
  Map<String, dynamic> get values;
}

@Schema()
abstract class $ReflectionRegisterParams {
  String get id;
  int get pid;
  String? get name;
  String? get genkitVersion;
  double? get reflectionApiSpecVersion;
  List<String>? get envs;
}

@Schema()
abstract class $ReflectionRunActionParams {
  String? get runtimeId;
  String get key;
  dynamic get input;
  dynamic get init;
  dynamic get context;
  Map<String, dynamic>? get telemetryLabels;
  bool? get stream;
  bool? get streamInput;
}

@Schema()
abstract class $ReflectionRunActionStateParams {
  String get requestId;
  Map<String, dynamic>? get state;
}

@Schema()
abstract class $ReflectionSendInputStreamChunkParams {
  String get requestId;
  Map<String, dynamic>? get chunk;
}

@Schema()
abstract class $ReflectionStreamChunkParams {
  String get requestId;
  dynamic get chunk;
}
