// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:genkit/schema.dart';
part 'types.schema.g.dart';

@GenkitSchema()
abstract class CandidateSchema {
  double get index;
  MessageSchema get message;
  GenerationUsageSchema? get usage;
  FinishReason get finishReason;
  String? get finishMessage;
  Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class MessageSchema {
  Role get role;
  List<PartSchema> get content;
  Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class ToolDefinitionSchema {
  String get name;
  String get description;
  dynamic get inputSchema;
  dynamic get outputSchema;
  Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class PartSchema {}

@GenkitSchema()
abstract class TextPartSchema implements PartSchema {
  String get text;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class MediaPartSchema implements PartSchema {
  MediaSchema get media;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class ToolRequestPartSchema implements PartSchema {
  ToolRequestSchema get toolRequest;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class ToolResponsePartSchema implements PartSchema {
  ToolResponseSchema get toolResponse;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class DataPartSchema implements PartSchema {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class CustomPartSchema implements PartSchema {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic> get custom;
}

@GenkitSchema()
abstract class ReasoningPartSchema implements PartSchema {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
  String get reasoning;
}

@GenkitSchema()
abstract class ResourcePartSchema implements PartSchema {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
  Map<String, dynamic> get resource;
}

@GenkitSchema()
abstract class MediaSchema {
  String? get contentType;
  String get url;
}

@GenkitSchema()
abstract class ToolRequestSchema {
  String? get ref;
  String get name;
  Map<String, dynamic>? get input;
  bool? get partial;
}

@GenkitSchema()
abstract class ToolResponseSchema {
  String? get ref;
  String get name;
  dynamic get output;
  List<dynamic>? get content;
}

@GenkitSchema()
abstract class ModelRequestSchema {
  List<MessageSchema> get messages;
  Map<String, dynamic>? get config;
  List<ToolDefinitionSchema>? get tools;
  String? get toolChoice;
  OutputConfigSchema? get output;
  List<DocumentDataSchema>? get docs;
}

@GenkitSchema()
abstract class ModelResponseSchema {
  MessageSchema? get message;
  FinishReason get finishReason;
  String? get finishMessage;
  double? get latencyMs;
  GenerationUsageSchema? get usage;
  Map<String, dynamic>? get custom;
  Map<String, dynamic>? get raw;
  GenerateRequestSchema? get request;
  OperationSchema? get operation;
}

@GenkitSchema()
abstract class ModelResponseChunkSchema {
  Role? get role;
  double? get index;
  List<PartSchema> get content;
  Map<String, dynamic>? get custom;
  bool? get aggregated;
}

@GenkitSchema()
abstract class GenerateRequestSchema {
  List<MessageSchema> get messages;
  Map<String, dynamic>? get config;
  List<ToolDefinitionSchema>? get tools;
  String? get toolChoice;
  OutputConfigSchema? get output;
  List<DocumentDataSchema>? get docs;
  double? get candidates;
}

@GenkitSchema()
abstract class GenerationUsageSchema {
  double? get inputTokens;
  double? get outputTokens;
  double? get totalTokens;
  double? get inputCharacters;
  double? get outputCharacters;
  double? get inputImages;
  double? get outputImages;
  double? get inputVideos;
  double? get outputVideos;
  double? get inputAudioFiles;
  double? get outputAudioFiles;
  Map<String, dynamic>? get custom;
  double? get thoughtsTokens;
  double? get cachedContentTokens;
}

@GenkitSchema()
abstract class OperationSchema {
  String? get action;
  String get id;
  bool? get done;
  Map<String, dynamic>? get output;
  Map<String, dynamic>? get error;
  Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class OutputConfigSchema {
  String? get format;
  Map<String, dynamic>? get schema;
  bool? get constrained;
  String? get contentType;
}

extension type FinishReason(String value) {
  static FinishReason get stop => FinishReason('stop');
  static FinishReason get length => FinishReason('length');
  static FinishReason get blocked => FinishReason('blocked');
  static FinishReason get interrupted => FinishReason('interrupted');
  static FinishReason get other => FinishReason('other');
  static FinishReason get unknown => FinishReason('unknown');
}
extension type Role(String value) {
  static Role get system => Role('system');
  static Role get user => Role('user');
  static Role get model => Role('model');
  static Role get tool => Role('tool');
}

@GenkitSchema()
abstract class DocumentDataSchema {
  List<PartSchema> get content;
  Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class GenerateActionOptionsSchema {
  String get model;
  List<DocumentDataSchema>? get docs;
  List<MessageSchema> get messages;
  List<String>? get tools;
  String? get toolChoice;
  Map<String, dynamic>? get config;
  GenerateActionOutputConfigSchema? get output;
  Map<String, dynamic>? get resume;
  bool? get returnToolRequests;
  int? get maxTurns;
  String? get stepName;
}

@GenkitSchema()
abstract class GenerateActionOutputConfigSchema {
  String? get format;
  String? get contentType;
  bool? get instructions;
  Map<String, dynamic>? get jsonSchema;
  bool? get constrained;
}
