// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:genkit/schema.dart';
part 'types.schema.g.dart';

@GenkitSchema()
abstract class CandidateSchema {
  external double get index;
  external MessageSchema get message;
  external GenerationUsageSchema? get usage;
  external FinishReason get finishReason;
  external String? get finishMessage;
}

@GenkitSchema()
abstract class MessageSchema {
  external Role get role;
  external List<PartSchema> get content;
  external Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class ToolDefinitionSchema {
  external String get name;
  external String get description;
  external dynamic? get inputSchema;
  external dynamic? get outputSchema;
  external Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class PartSchema {}

@GenkitSchema()
abstract class TextPartSchema implements PartSchema {
  external String get text;
  external dynamic? get metadata;
  external dynamic? get custom;
}

@GenkitSchema()
abstract class MediaPartSchema implements PartSchema {
  external MediaSchema get media;
  external dynamic? get metadata;
  external dynamic? get custom;
}

@GenkitSchema()
abstract class ToolRequestPartSchema implements PartSchema {
  external ToolRequestSchema get toolRequest;
  external dynamic? get metadata;
  external dynamic? get custom;
}

@GenkitSchema()
abstract class ToolResponsePartSchema implements PartSchema {
  external ToolResponseSchema get toolResponse;
  external dynamic? get metadata;
  external dynamic? get custom;
}

@GenkitSchema()
abstract class DataPartSchema implements PartSchema {
  external dynamic? get metadata;
  external Map<String, dynamic>? get custom;
}

@GenkitSchema()
abstract class CustomPartSchema implements PartSchema {
  external Map<String, dynamic>? get metadata;
  external Map<String, dynamic> get custom;
}

@GenkitSchema()
abstract class ReasoningPartSchema implements PartSchema {
  external dynamic? get metadata;
  external dynamic? get custom;
  external String get reasoning;
}

@GenkitSchema()
abstract class ResourcePartSchema implements PartSchema {
  external dynamic? get metadata;
  external dynamic? get custom;
  external Map<String, dynamic> get resource;
}

@GenkitSchema()
abstract class MediaSchema {
  external String? get contentType;
  external String get url;
}

@GenkitSchema()
abstract class ToolRequestSchema {
  external String? get ref;
  external String get name;
}

@GenkitSchema()
abstract class ToolResponseSchema {
  external String? get ref;
  external String get name;
}

@GenkitSchema()
abstract class ModelRequestSchema {
  external dynamic get messages;
  external dynamic? get tools;
  external dynamic? get toolChoice;
  external dynamic? get output;
  external dynamic? get docs;
}

@GenkitSchema()
abstract class ModelResponseSchema {
  external dynamic? get message;
  external FinishReason get finishReason;
  external dynamic? get finishMessage;
  external dynamic? get latencyMs;
  external dynamic? get usage;
  external dynamic? get request;
  external dynamic? get operation;
}

@GenkitSchema()
abstract class ModelResponseChunkSchema {
  external dynamic? get role;
  external dynamic? get index;
  external dynamic get content;
  external dynamic? get aggregated;
}

@GenkitSchema()
abstract class GenerationUsageSchema {
  external double? get inputTokens;
  external double? get outputTokens;
  external double? get totalTokens;
  external double? get inputCharacters;
  external double? get outputCharacters;
  external double? get inputImages;
  external double? get outputImages;
  external double? get inputVideos;
  external double? get outputVideos;
  external double? get inputAudioFiles;
  external double? get outputAudioFiles;
  external Map<String, dynamic>? get custom;
  external double? get thoughtsTokens;
  external double? get cachedContentTokens;
}

@GenkitSchema()
abstract class OperationSchema {
  external String? get action;
  external String get id;
  external bool? get done;
  external Map<String, dynamic>? get error;
  external Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class OutputConfigSchema {
  external String? get format;
  external Map<String, dynamic>? get schema;
  external bool? get constrained;
  external String? get contentType;
}

extension type FinishReason(String value) {
  static FinishReason get stop => FinishReason('stop');
  static FinishReason get length => FinishReason('length');
  static FinishReason get blocked => FinishReason('blocked');
  static FinishReason get interrupted => FinishReason('interrupted');
  static FinishReason get other => FinishReason('other');
  static FinishReason get unknown => FinishReason('unknown');
}
extension type Role(String value) {
  static Role get system => Role('system');
  static Role get user => Role('user');
  static Role get model => Role('model');
  static Role get tool => Role('tool');
}

@GenkitSchema()
abstract class DocumentDataSchema {
  external List<PartSchema> get content;
  external Map<String, dynamic>? get metadata;
}

@GenkitSchema()
abstract class GenerateActionOptionsSchema {
  external String get model;
  external List<DocumentDataSchema>? get docs;
  external List<MessageSchema> get messages;
  external List<String>? get tools;
  external String? get toolChoice;
  external GenerateActionOutputConfigSchema? get output;
  external Map<String, dynamic>? get resume;
  external bool? get returnToolRequests;
  external double? get maxTurns;
  external String? get stepName;
}

@GenkitSchema()
abstract class GenerateActionOutputConfigSchema {
  external String? get format;
  external String? get contentType;
  external bool? get instructions;
  external bool? get constrained;
}
