// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:genkit/plugin.dart';
import 'package:meta/meta.dart';
import 'package:schemantic/schemantic.dart';

import 'common_plugin.dart';
import 'generated/generativelanguage.dart' as gcl;

part 'imagen.g.dart';

/// Request options for Imagen models on the Gemini API.
///
/// Unknown keys pass through to the predict `parameters` object, so newer
/// API parameters (for example `imageSize`) work without a schema change.
@Schema(additionalProperties: true)
abstract class $ImagenOptions {
  @StringField(
    description: 'Override the API key provided at plugin initialization.',
  )
  String? get apiKey;

  @IntegerField(
    minimum: 1,
    maximum: 4,
    description:
        'The number of images to generate, from 1 to 4 (inclusive). '
        'The default is 1.',
  )
  int? get numberOfImages;

  @StringField(
    enumValues: ['1:1', '9:16', '16:9', '3:4', '4:3'],
    description: 'Desired aspect ratio of the output image.',
  )
  String? get aspectRatio;

  @StringField(
    enumValues: ['dont_allow', 'allow_adult', 'allow_all'],
    description:
        'Control if/how images of people will be generated by the model.',
  )
  String? get personGeneration;
}

/// Imagen models the googleai plugin curates capability metadata for.
///
/// Each value pairs a bare model [id] (no plugin prefix) with a display
/// [label]. Other `imagen-*` names still resolve dynamically with the shared
/// [imagenModelInfo] capabilities.
enum KnownImagenModel {
  imagen4('imagen-4.0-generate-001', 'Imagen 4'),
  imagen4Fast('imagen-4.0-fast-generate-001', 'Imagen 4 Fast'),
  imagen4Ultra('imagen-4.0-ultra-generate-001', 'Imagen 4 Ultra');

  const KnownImagenModel(this.id, this.label);

  /// Bare model name (no plugin prefix).
  final String id;

  /// Human-readable label surfaced in listings.
  final String label;

  /// The capability profile for this model.
  ModelInfo get info => ModelInfo(
    label: label,
    // Unmodifiable: curated entries are shared across every resolution of the
    // model, so accidental mutation through action metadata must fail loudly.
    supports: Map.unmodifiable(_imagenSupports),
    stage: 'stable',
  );
}

const _imagenSupports = {
  'media': true,
  'multiturn': false,
  'tools': false,
  'toolChoice': false,
  'systemRole': false,
  'output': ['media'],
};

/// Capability metadata for `imagen-*` models not in [knownImagenModels].
final imagenModelInfo = ModelInfo(supports: Map.unmodifiable(_imagenSupports));

/// Curated capability metadata for known Imagen models, keyed by bare model
/// name (no plugin prefix). Derived from [KnownImagenModel].
final knownImagenModels = <String, ModelInfo>{
  for (final model in KnownImagenModel.values) model.id: model.info,
};

bool isImagenModelName(String name) => name.startsWith('imagen-');

/// Whether a discovered [model] should be surfaced as an Imagen model:
/// an `imagen-*` name that serves `:predict` and is not marked deprecated.
bool isDiscoveredImagenModel(gcl.Model model) {
  final name = model.name;
  if (name == null || !name.startsWith('models/imagen-')) return false;
  if (model.supportedGenerationMethods?.contains('predict') != true) {
    return false;
  }
  return model.description?.contains('deprecated') != true;
}

/// Capability metadata for [modelName], falling back to [imagenModelInfo]
/// for names not curated in [knownImagenModels].
ModelInfo imagenModelInfoFor(String modelName) =>
    knownImagenModels[modelName] ?? imagenModelInfo;

Model<ImagenOptions> createImagenModel(
  CommonGoogleGenPlugin plugin,
  String modelName,
) {
  return Model(
    name: '${plugin.name}/$modelName',
    customOptions: ImagenOptions.$schema,
    metadata: {'model': imagenModelInfoFor(modelName).toJson()},
    fn: (req, ctx) async {
      if (req == null) {
        throw GenkitException(
          'Imagen requires a generation request.',
          status: StatusCodes.INVALID_ARGUMENT,
        );
      }
      if (ctx.streamingRequested) {
        throw GenkitException(
          'Imagen models do not support streaming.',
          status: StatusCodes.INVALID_ARGUMENT,
        );
      }
      if (req.tools?.isNotEmpty ?? false) {
        throw GenkitException(
          'Imagen models do not support tools.',
          status: StatusCodes.INVALID_ARGUMENT,
        );
      }

      final options = ImagenOptions.fromJson(req.config ?? {});
      final prompt = extractImagenPrompt(req);
      if (prompt.isEmpty) {
        throw GenkitException(
          'Imagen requires a non-empty text prompt.',
          status: StatusCodes.INVALID_ARGUMENT,
        );
      }
      final image = extractImagenImage(req);

      final service = await plugin.getApiClient(options.apiKey);
      try {
        final response = await service.predict({
          'instances': [
            {'prompt': prompt, 'image': ?image},
          ],
          'parameters': toImagenParameters(options),
        }, model: 'models/$modelName');

        final predictions = (response['predictions'] as List?) ?? const [];
        if (predictions.isEmpty) {
          throw GenkitException(
            'Model returned no predictions. Possibly due to content filters.',
            status: StatusCodes.FAILED_PRECONDITION,
          );
        }

        final message = Message(
          role: Role.model,
          content: predictions.map(fromImagenPrediction).toList(),
        );
        return ModelResponse(
          finishReason: FinishReason.stop,
          message: message,
          raw: response,
          usage: GenerationUsage(
            inputCharacters: prompt.length.toDouble(),
            inputImages: image == null ? 0 : 1,
            outputImages: message.content.length.toDouble(),
          ),
        );
      } catch (e, stack) {
        throw plugin.handleException(e, stack);
      } finally {
        service.client.close();
      }
    },
  );
}

/// Joins the text parts of the last message into the predict prompt.
@visibleForTesting
String extractImagenPrompt(ModelRequest request) {
  final last = request.messages.lastOrNull;
  if (last == null) return '';
  return last.content.where((p) => p.isText).map((p) => p.text ?? '').join();
}

/// Extracts the base image for image editing from the last message: the first
/// data-URI media part carrying either no metadata `type` or type `base`.
@visibleForTesting
Map<String, String>? extractImagenImage(ModelRequest request) {
  final last = request.messages.lastOrNull;
  if (last == null) return null;
  for (final part in last.content) {
    if (!part.isMedia) continue;
    final type = part.metadata?['type'];
    if (type != null && type != 'base') continue;
    final url = part.media!.url;
    final separator = url.indexOf(',');
    if (!url.startsWith('data:') || separator == -1) continue;
    return {'bytesBase64Encoded': url.substring(separator + 1)};
  }
  return null;
}

@visibleForTesting
Map<String, dynamic> toImagenParameters(ImagenOptions options) {
  final params = <String, dynamic>{
    'sampleCount': options.numberOfImages ?? 1,
    ...options.toJson(),
  };
  params
    ..remove('numberOfImages')
    ..remove('apiKey')
    ..removeWhere((_, value) => value == null);
  return params;
}

@visibleForTesting
MediaPart fromImagenPrediction(Object? prediction) {
  final b64Data = prediction is Map ? prediction['bytesBase64Encoded'] : null;
  if (b64Data is! String || b64Data.isEmpty) {
    throw GenkitException(
      'Imagen prediction did not include image bytes.',
      status: StatusCodes.INTERNAL,
    );
  }
  final mimeType = (prediction as Map)['mimeType'] as String? ?? 'image/png';
  return MediaPart(
    media: Media(url: 'data:$mimeType;base64,$b64Data', contentType: mimeType),
  );
}
