builders:
  genkit_schema_builder:
    import: "package:genkit_schema_builder/builder.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: {".dart": [".schema.g.dart"]}
    auto_apply: dependents
    build_to: source

targets:
  $default:
    builders:
      genkit_schema_builder:
        enabled: true
